export const C = {
  black: '#0B0C10',
  graphite: '#1F232B',
  red: '#FF3B30',
  lime: '#CCFF00',
  teal: '#1D9E75',
  tealHover: '#189060',
  white: '#FFFFFF',
  gray: '#A0A8B8',
  gray2: '#6B7280',
  border: 'rgba(255,255,255,0.07)',
  borderLime: 'rgba(204,255,0,0.2)',
} as const

export type ColorKey = keyof typeof C

/** Shared style tokens reutilizables entre componentes */
export const T = {
  card: {
    background: C.graphite,
    border: `1px solid ${C.border}`,
    borderRadius: 14,
    padding: '20px 24px',
  },
  statCard: {
    background: C.graphite,
    border: `1px solid ${C.border}`,
    borderRadius: 14,
    padding: '20px 22px',
  },
  pageHead: {
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: -1,
    color: C.white,
  },
  pageSub: {
    fontSize: 13,
    color: C.gray,
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: C.white,
    marginBottom: 16,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
  },
  th: {
    textAlign: 'left' as const,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    color: C.gray,
    padding: '10px 14px',
    borderBottom: `1px solid ${C.border}`,
  },
  td: {
    padding: '12px 14px',
    fontSize: 14,
    color: C.gray,
    borderBottom: 'rgba(255,255,255,0.04) 1px solid',
  },
  tdW: {
    padding: '12px 14px',
    fontSize: 14,
    color: C.white,
    borderBottom: 'rgba(255,255,255,0.04) 1px solid',
    fontWeight: 500,
  },
  btnRed: {
    background: C.red,
    color: C.white,
    border: 'none',
    padding: '9px 18px',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
  },
  btnGhost: {
    background: 'transparent',
    color: C.gray,
    border: `1px solid ${C.border}`,
    padding: '7px 14px',
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnLime: {
    background: 'transparent',
    color: C.lime,
    border: `1px solid rgba(204,255,0,0.2)`,
    padding: '7px 14px',
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnPrimary: {
    background: '#1D9E75',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: 6,
    padding: '9px 16px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
} as const
